### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Luca1995** [sl4v3k/Plasticity_crack#1]
Hi, 
first of, thanks for your work. I am trying to understand how you read and where to get info. I already own IDA but I am still very newbie. I tried to follow the .README, so I just copypasted the 2 dll inside the Renderer folder. My result is a black screen (plasticity app window is just fully black). 
I guess I am skipping a Step, can you please help me?

**Comment by Luca1995** [comment]
This is the directory I put the .dll in:
C:\Program Files\Plasticity\app-1.4.10\resources\app\.webpack\renderer
So I guess it is 1.4.10, Iam supposed to block any incoming connection in windows firewall?

**Comment by sl4v3k** [comment]
i just reinstalled 1.4.10 from scratch and all works fine. Location is correct i mean D:\Plasticity\app-1.4.11\resources\app\.webpack\renderer

**Comment by sl4v3k** [comment]
heh, just realised that now i downloaded and is version 1.4.11 but patch works. No black screen, gives me full Export and Import, all SUDIO_FEATURES

**Comment by sl4v3k** [comment]
if You want give me TeamViewr access i can see whats wrong

**Comment by Luca1995** [comment]
Hi, is there a way to send you oTW access privately?

**Comment by sl4v3k** [comment]
give me Your email

**Comment by Luca1995** [comment]
lbaeli95@gmail.com

**Comment by mearuk** [comment]
First of all, I can't thank you enough for explaining the methods and for your efforts on this subject. 
I have the same problem with Luca, I would really like to know what you are doing to avoid this problem.

**Comment by sl4v3k** [comment]
The problem was about VC 2019 Redistributables missing. So download new dlls from git and install Redistributables from microsoft. Will fix the "Black Screen" issue
